version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.16
    steps:
      - checkout
      - run:
          name: Package to workflow file
          command: ../ci/package.sh
      - store_artifacts:
        path: bin/gdrive-alfred.alfredworkflow
        destination: gdrive-alfred.alfredworkflow
workflows:
  version: 2
  build:
    jobs:
      - build
