version: 2
jobs:
  package:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Package to workflow file
          command: ci/package.sh
      - store_artifacts:
          path: bin/gdrive-alfred.alfredworkflow
          destination: gdrive-alfred.alfredworkflow
      - run:
          name: Create GH Release
          command: ci/release_if_new_version.sh
  test_py27:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - checkout
      - run:
          name: e2e test
          command: tests/e2e.sh
  test_py34:
    docker:
      - image: circleci/python:3.4
    steps:
      - checkout
      - run:
          name: e2e test
          command: tests/e2e.sh
workflows:
  version: 2
  test_and_package:
    jobs:
      - test_py27
      - test_py34
      - package:
          requires:
            - test_py27
            - test_py34
